【添加】UM 文件
RT-Thread-packages/webclient pull request #22
Opened 2018-08-12 11:05 UTC by chenyong111

2018-08-12 12:36 UTC, armink requested changes

2018-08-12 12:36 UTC, armink commented on README.md
> +WebClient 软件包是 RT_Thread 自主研发的，基于 HTTP 协议的客户端的实现，它提供设备与 HTTP Server 的通讯的基本功能。
RT-Thread

2018-08-12 12:36 UTC, armink commented on README.md
> +- 如何从零开始使用，请参考 [用户手册](docs/user-guide.md)
用户指南

2018-08-12 12:36 UTC, armink commented on README.md
> +- 详细的示例介绍，请参考 [示例文档](docs/samples.md)
把示例放在用户指南的前面吧，感觉是先操作示例会更加显得由浅入深。

2018-08-12 12:36 UTC, armink commented on README.md
> + - WebClient 软件包版本更新（`V1.0.0 -> V2.0.0`）后软件包中函数接口和使用流程都有所变化，若开发者代码中使用之前接口，可以适配最新版本接口，或者在版本号配置中选择 `V1.0.0` 版本。
`V1.0.0 -> 当前最新版V2.0.0`

2018-08-12 12:36 UTC, armink commented on README.md
> + - WebClient 软件包版本更新（`V1.0.0 -> V2.0.0`）后软件包中函数接口和使用流程都有所变化，若开发者代码中使用之前接口，可以适配最新版本接口，或者在版本号配置中选择 `V1.0.0` 版本。
1.0.0=>2.0.0 的迁移指南好像没有看到

2018-08-12 12:36 UTC, armink commented on docs/introduction.md
> +- 支持 GET/POST 命令
这些叫 **请求方法** 更合适吧，而不是命令： https://baike.baidu.com/item/HTTP%E8%AF%B7%E6%B1%82

2018-08-12 12:36 UTC, armink commented on docs/introduction.md
> +    HTTP头部信息用于确定当前请求或响应的信息，在发送 GET 请求时头部的拼接成为用户操作的一大难题，正常的做法是手动逐行输入或使用字符串拼接方式，WebClient 软件包中提供 `类正则表达式方式` 添加 GET 请求头部信息，方便用户使用。对于 POST 返回的头部信息，往往用户需要获取头部对应信息，WebClient 软件包同样提供了 `通过头域名称获取域值方式`，方便获取需要的
`通过头域名称获取域值方式` 这段挺难理解的

2018-08-12 12:36 UTC, armink commented on docs/principle.md
> +![WebClient 软件包工作原理](./figures/browse-http-Server.jpg)
服务器端，**返回响应** 的框放在 **接收请求** 框的下面，纵轴代表时间轴，这样会更直观

而且图的内容保证能够下面的流程介绍保证一致

2018-08-12 12:36 UTC, armink commented on docs/samples.md
> +## 启动例程
这一节能不能跟 **示例工作流程** 合并。在一个大节内，按照 GET 及 POST  请求，独立两个在子章节来介绍示例

2018-08-12 12:36 UTC, armink commented on docs/samples.md
> +## 启动例程
而且在示例工作流程中不用过多介绍代码细节是如何实现的（毕竟是工作流程，不是实现流程），告诉用户你现在这个示例在做什么，会有什么样的结果，如何判断结果就好，让读者傻瓜式的方式了解我们的软件包能干什么样的活就好。具体咋实现的，他就需要对着我们源码、用户指南详细阅读。

2018-08-12 12:36 UTC, armink commented on docs/samples.md
> +[I/WEB] webclient GET request response data :
这一行 INFO 日志有点奇怪，是不是应该是 DEBUG

2018-08-12 12:36 UTC, armink commented on docs/user-guide.md
> +int content_length = session->content_length;
get_content_length 的 API 目前还没有吗？

2018-08-12 12:36 UTC, armink commented on docs/user-guide.md
> +    if(webclient_get(session, URI, header) != 200)
这个 API 入参不对

2018-08-12 12:36 UTC, armink commented on docs/user-guide.md
> +    free(result);
使用 web_free ?

2018-08-12 12:36 UTC, armink commented on docs/user-guide.md
> +	webclient_close(session);
示例里的所有代码都在格式化工具格式化下

2018-08-12 12:36 UTC, armink commented on docs/user-guide.md
> +- 分段数据 POST 请求
这几种方式，分别哪些场景下使用，重点说明下

2018-08-12 12:36 UTC, armink commented on docs/user-guide.md
> +[web]not support https connect, please enable webclient https configure!
日志格式及内容更新

2018-08-12 12:36 UTC, armink commented on docs/api.md
> +## 发送数据
读取数据

2018-08-12 12:36 UTC, armink commented on docs/api.md
> +## 接收数据
同上问题

2018-08-12 12:36 UTC, armink commented on docs/api.md
> +## 设置请求发送的头部信息
在请求头中添加字段

2018-08-12 12:36 UTC, armink commented on docs/api.md
> +|fmt                | 添加头部信息的表达式                 |
字段信息

2018-08-12 12:36 UTC, armink commented on docs/api.md
> +|fields             | HTTP 头域名称                 |
fileds 意为字段，详见：https://zh.wikipedia.org/zh-hans/HTTP头字段

文档中涉及到的都需要改掉

2018-08-12 18:18 UTC, Lawlieta commented on docs/principle.md
> +![WebClient 软件包工作原理](./figures/browse-http-Server.jpg)
没太明白怎么改的，明天在确定一下

2018-08-12 18:18 UTC, Lawlieta commented on docs/samples.md
> +[I/WEB] webclient GET request response data :
这个后面改为了rt_kprintf ，我这边更新一下

2018-08-12 18:18 UTC, Lawlieta commented on docs/user-guide.md
> +int content_length = session->content_length;
没有，其实可以通过 `webclient_header_fields_get` 函数获取

2018-08-13 00:12 UTC, armink commented on docs/user-guide.md
> +int content_length = session->content_length;
要不然加一个 api 把，毕竟常用

2018-08-13 00:36 UTC, armink commented
1.0.0=>2.0.0 的迁移指南好像没有看到

2018-08-13 00:36 UTC, armink commented on docs/samples.md
> +> HTTP 收发数据包括头部数据和实际数据两部分，以下称头部数据为 `header 数据`, 实际数据为 `body 数据`。
实际数据 是啥意思

2018-08-13 00:36 UTC, armink commented on docs/user-guide.md
> +    多用于上传文件较小的 POST 请求。
POST 内容，而不是文件

2018-08-13 05:53 UTC, merged