add webclient tls support
RT-Thread-packages/webclient pull request #7
Opened 2018-01-25 12:20 UTC by chenyong111

2018-01-26 14:54 UTC, BernardXiong commented on webclient.c
> +#ifdef PKG_USING_WEBCLIENT_TLS
webclient_tls不是独立的包，所以宏选项不应该使用PKG_USING_

2018-01-26 14:59 UTC, BernardXiong commented on webclient.c
> +    if(strncmp(URI, "https://", 8) == 0)
是否在webclient_connect中处理http/https会更合理？而不需要在每个webclient_open都去处理一遍https的协议？

2018-01-26 15:01 UTC, BernardXiong commented on webclient_internal.h
> +#ifdef RT_USING_PSRAM
PSRAM需要有一份统一规划。有两种模式：
1. malloc/free统一丢到低速内存区；KERNEL_MALLOC/FREE统一丢到高速内存区；
2. malloc/free放于高速内存区，扩展的sdram_malloc或psram_malloc丢到低速区；或者把这部分内存区域简单定义为ext_malloc/free。

这个地方大家可以讨论下。直接PSRAM、SDRAM感觉都不是太合理。

2018-01-27 01:03 UTC, armink requested changes

2018-01-27 01:03 UTC, armink commented on webclient.c
> +            session->tls_session->host = rt_strdup(host_addr_new);
`session->tls_session->host != NULL` 时，是不是应该先执行 free，再进行 dup

2018-01-27 01:03 UTC, armink commented on webclient.c
> +            session->tls_session->port = rt_strdup(port_tls_str);
同 `L299`

2018-01-27 01:03 UTC, armink commented on webclient.c
> +    rt_kprintf("don't support TLS protocol, check your menuconfig!\n");
既然不支持 TLS ，是不是应该将整个函数都包裹在 `#ifdef PKG_WEBCLIENT_USING_TLS` 下，不让用户访问到该 API。

2018-01-27 01:03 UTC, armink commented on webclient_internal.h
> +#ifdef RT_USING_PSRAM
对于 PSRAM 感觉定义为 ext_malloc/free 还是比较贴切的。

这里使用 PSRAM、SDRAM 这类私有宏定义，会导致库的限制性太强。

作为通用的 package ，把 malloc/free 抽象出来，用户在 `.h` 中手工可配置就好。

2018-01-30 04:07 UTC, BernardXiong commented
请更改 PKG_USING_WEBCLIENT_TLS 宏的名称，PKG_USING_仅提供出来给一个独立包使用。

2018-01-30 04:07 UTC, closed without merging